### ISSUE TITLE
Channel arg is not required on slack

### ISSUE THREAD

**Issue by dinopetrone** [iktakahiro/slackpy#14]
Change the initialize to not require it:

```
def __init__(self, web_hook_url, channel=None, username='Logger'):

        self.web_hook_url = web_hook_url
        self.channel = channel
        self.username = username
```

This will then take the default channel that the hook was created with and send to that.  this allows for private channels to get used.

**Comment by iktakahiro** [comment]
Hi @dinopetrone 
That's true. I'll modify after operation verification.

**Comment by iktakahiro** [comment]
Hi @dinopetrone,
I disolved this issue. Thank you for your feedback.
